name: layout_practice
description: This is a practice layout project.


publish_to: 'none'


version: 1.0.0+1


environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  context_menus: ^1.0.2
  
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/data.json
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
